#pragma once

namespace SatelliteApi
{
    enum class SatelliteCategory : int
    {
        All = 0,
        Brightest = 1,
        ISS = 2,
        Weather = 3,
        NOAA = 4,
        GOES = 5,
        EarthResources = 6,
        SearchAndRescue = 7,
        DisasterMonitoring = 8,
        TrackingAndDataRelaySatelliteSystem = 9,
        Geostationary = 10,
        Intelsat = 11,
        Gorizont = 12,
        Raduga = 13,
        Molniya = 14,
        Iridium = 15,
        Orbcomm = 16,
        Globalstar = 17,
        AmateurRadio = 18,
        Experimental = 19,
        GPSOperational = 20,
        GlonassOperational = 21,
        Galileo = 22,
        SatelliteBasedAugmentationSystem = 23,
        NavyNavigationSatelliteSystem = 24,
        RussianLEONavigation = 25,
        SpaceAndEarthScience = 26,
        Geodetic = 27,
        Engineering = 28,
        Education = 29,
        Military = 30,
        RadarCalibration = 31,
        CubeSats = 32,
        XMandSirius = 33,
        TV = 34,
        BeidouNavigationSystem = 35,
        Yaogan = 36,
        WestfordNeedles = 37,
        Parus = 38,
        Strela = 39,
        Gonets = 40,
        Tsiklon = 41,
        Tsikada = 42,
        O3BNetworks = 43,
        Tselina = 44,
        Celestis = 45,
        IRNSS = 46,
        QZSS = 47,
        Flock = 48,
        Lemur = 49,
        GPSConstellation = 50,
        GlonassConstellation = 51,
        Starlink = 52,
        OneWeb = 53,
        ChineseSpaceStation = 54,
        Qianfan = 55,
        Kuiper = 56
    };
}